Add Key.donor_id property, add rep command
giveaway-bot-v2/ga-bot pull request #1
Opened 2021-07-09 16:04 UTC by dannyhpy

I didn't test it yet

2021-07-09 16:26 UTC, dannyhpy commented
```js
src/commands/rep.ts(35,9): error TS2322: Type 'User' is not assignable to type 'void'.
src/commands/rep.ts(35,57): error TS2345: Argument of type 'bigint' is not assignable to parameter of type '`${bigint}`'.
src/commands/rep.ts(38,9): error TS2322: Type 'User' is not assignable to type 'void'.
src/commands/rep.ts(38,57): error TS2345: Argument of type 'bigint' is not assignable to parameter of type '`${bigint}`'.
src/commands/setup.ts(3,32): error TS2305: Module '"discord.js"' has no exported member 'MessageComponentInteractionCollector'.
src/commands/setup.ts(19,28): error TS7006: Parameter 'collected' implicitly has an 'any' type.
src/commands/setup.ts(52,18): error TS2551: Property 'setCustomID' does not exist on type 'MessageButton'. Did you mean 'setCustomId'?
src/commands/setup.ts(56,18): error TS2551: Property 'setCustomID' does not exist on type 'MessageButton'. Did you mean 'setCustomId'?
src/commands/setup.ts(64,29): error TS7006: Parameter 'collected' implicitly has an 'any' type.
src/commands/setup.ts(66,31): error TS2345: Argument of type 'Message | APIMessage' is not assignable to parameter of type 'MessageResolvable | "@original"'.
src/commands/setup.ts(106,16): error TS2551: Property 'setCustomID' does not exist on type 'MessageButton'. Did you mean 'setCustomId'?
src/commands/setup.ts(117,33): error TS2345: Argument of type 'Message | APIMessage' is not assignable to parameter of type 'MessageResolvable | "@original"'.
  Type 'APIMessage' is not assignable to type 'MessageResolvable | "@original"'.
    Type 'APIMessage' is missing the following properties from type 'Message': patch, applicationId, channel, cleanContent, and 37 more.
src/core/GiveawayManager.ts(2,20): error TS7016: Could not find a declaration file for module 'pg-cursor'. '/home/node/node_modules/pg-cursor/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/pg-cursor` if it exists or add a new declaration (.d.ts) file containing `declare module 'pg-cursor';`
src/core/GiveawayManager.ts(66,22): error TS2551: Property 'customID' does not exist on type 'ButtonInteraction'. Did you mean 'customId'?
src/core/GiveawayManager.ts(68,71): error TS2551: Property 'customID' does not exist on type 'ButtonInteraction'. Did you mean 'customId'?
src/core/utils.ts(21,10): error TS2551: Property 'setCustomID' does not exist on type 'MessageButton'. Did you mean 'setCustomId'?
```

2021-07-09 17:33 UTC, Bluenix2 commented
Just as an update..

I am working on pin-pointing a commit in the `package.json` file so that we don't get these issues. Currently waiting on a couple of pull requests.

2021-07-10 19:48 UTC, Bluenix2 reviewed
Great work so far Danny!

2021-07-10 19:48 UTC, Bluenix2 commented on src/commands/rep.ts
> +  ];
I haven't looked *too* hard into it, but could we perhaps use subcommands for this?

2021-07-10 19:48 UTC, Bluenix2 commented on src/database/GiveawayTable.ts
> +   * Get the latest won giveaway by a certain user.
```suggestion
   * Get the latest giveaway the user won.
```

2021-07-10 19:48 UTC, Bluenix2 commented on src/database/GiveawayTable.ts
> +   * @returns The latest found giveaway, or null
```suggestion
   * @returns The latest giveaway found, or null
```

2021-07-10 19:48 UTC, Bluenix2 commented on src/database/GiveawayTable.ts
> +  async getLastWonGiveawayBy(id: Snowflake, connection?: PoolClient): Promise<Giveaway | null> {
```suggestion
  async getLastWon(id: Snowflake, connection?: PoolClient): Promise<Giveaway | null> {
```

2021-07-10 19:48 UTC, Bluenix2 commented on src/database/GiveawayTable.ts
> +      name: 'GiveawayTable_getLastWonGiveawayBy',
```suggestion
      name: 'GiveawayTable_getLastWon',
```

2021-07-10 19:48 UTC, Bluenix2 commented on src/database/KeyTable.ts
>        values: [value, message],
```suggestion
      text:'INSERT INTO keys (donor_id, value, message) VALUES ($1, $2, $3) RETURNING *;',
      values: [donor_id, value, message],
```

2021-07-10 19:48 UTC, Bluenix2 commented on src/commands/rep.ts
> +    switch (rep) {
```suggestion
    // TODO: Check if the user already gave a reputation point

    switch (interaction.options.get('rep')?.value) {
```

2021-07-10 19:48 UTC, Bluenix2 commented on src/database/UserTable.ts
> +  claimed_keys: number;
I don't yet have this in the giveaway loop, I'll add it when I do.
```suggestion
```

2021-07-10 19:48 UTC, Bluenix2 commented on src/database/UserTable.ts
> +        claimed_keys NOT NULL DEFAULT 0
```suggestion
        donated_keys NOT NULL DEFAULT 0
```

2021-07-10 19:48 UTC, Bluenix2 commented on src/database/UserTable.ts
> +  }
Do we need both?

2021-07-10 19:48 UTC, Bluenix2 commented on src/database/UserTable.ts
> +  }
Why have an increment number? Surely we will only ever increment it by 1.

2021-07-10 19:48 UTC, Bluenix2 commented on src/database/UserTable.ts
> +   * Get an user.
```suggestion
   * Get a user by its ID.
```

2021-07-10 19:48 UTC, Bluenix2 commented on src/commands/rep.ts
> +  ignoreGuilds = true;
I changed this because it's kind of backwards. It should be `DMOnly`.

2021-07-10 19:48 UTC, Bluenix2 commented on src/commands/rep.ts
> +    if (lastKey == null) return interaction.reply("You're not allowed to use that command at the moment.");
Can we add some spaces here? It's a bit unreadable right now

2021-07-10 19:48 UTC, Bluenix2 commented on src/commands/rep.ts
> +    const donor_id = lastKey.donor_id;
Kind of uneccessary shortcut.

2021-07-10 19:48 UTC, Bluenix2 commented on src/commands/rep.ts
> +    const conn = await interaction.client.db.connect();
You never release this connection

2021-07-13 16:15 UTC, Bluenix2 commented on src/database/UserTable.ts
> +  user_id: bigint;
As we agreed this should be a discord.js Snowflake

2021-07-13 16:16 UTC, Bluenix2 commented on src/database/KeyTable.ts
> +  donor_id: bigint;
This should be typed as a discord.js Snowflake as well

2021-07-20 10:56 UTC, Bluenix2 requested changes

2021-07-20 10:56 UTC, Bluenix2 commented on src/commands/rep.ts
> +  description = 'Either give a good or a bad reputation point to an user.';
I think there's improvements to be made on this, perhaps just simplifying it to:
```suggestion
  description = 'Give the donator of your last won giveaway a reputation point.';
```

2021-07-20 10:56 UTC, Bluenix2 commented on src/commands/rep.ts
> +      required: true
If I am not mistaken subcommands cannot have `required`.

2021-07-20 10:56 UTC, Bluenix2 commented on src/commands/rep.ts
> +    if (lastKey == null) return interaction.reply("No key was found on your latest giveaway.");
Could you add a comment here that this will never happen, but we do it for the typing.

2021-07-20 10:56 UTC, Bluenix2 commented on src/commands/rep.ts
> +  async bad(interaction: CommandInteraction): Promise<void> {
These two methods do basically the same thing, can you create a "middle-man" method (perhaps called `give` or similar). It takes the connection, interaction, and what increment for the rep - and will grab the last key and giveaway like this code does.

2021-07-20 10:56 UTC, Bluenix2 commented on src/database/GiveawayTable.ts
> +  async setRepGiven(id: number, given: boolean, connection?: PoolClient): Promise<void> {
Can you add a JSDoc here?

2021-07-20 10:56 UTC, Bluenix2 commented on src/database/UserTable.ts
> +   * Insert or update an user (upsert).
```suggestion
   * Insert or update a user (upsert).
```

2021-07-20 10:56 UTC, Bluenix2 commented on src/database/UserTable.ts
> +   * Increment reputation of an user (upsert).
```suggestion
   * Increment reputation of a user (upsert).
```

2021-07-20 10:56 UTC, Bluenix2 commented on src/database/UserTable.ts
> +  async incrementRep(id: Snowflake, reputationInc: number, connection?: PoolClient): Promise<User> {
It should be safe to assume that the user is already in the database (they have claimed enough keys to be able to donate) so we may not need to upsert. Besides, I am not sure if the update will work? Hopefully `reputation + $2` takes the form of `0 + $2` because of our default.

2021-07-20 10:56 UTC, Bluenix2 commented on src/database/UserTable.ts
> +   * Increment donated keys of an user (upsert).
```suggestion
   * Increment donated keys of a user (upsert).
```

2021-07-20 10:56 UTC, Bluenix2 commented on src/database/UserTable.ts
> +   * @param donatedKeysInc Donated keys increment
```suggestion
   * @param donatedKeysInc How much the increment the donated keys value
```

2021-07-20 12:32 UTC, Bluenix2 commented on src/commands/rep.ts
> +      if (lastGiveaway.rep_given === true) {
I am not completely convinced, but maybe make this a `else if`?

2021-07-20 12:32 UTC, Bluenix2 commented on src/commands/rep.ts
> +      await interaction.client.db.giveaways.setRepGiven(lastGiveaway.id, true, conn);
The more I think about - why not combine these functions into one. Have a method on the user table that takes an id and increments rep as well as sets that check. I think something like the following query should work:
```sql
WITH (
    SELECT id, key FROM giveaways WHERE winner = $1 ORDER BY timestamp DESC;
) AS last_giveaway;
UPDATE giveaways SET rep_given = TRUE WHERE id = last_giveaway.id;
UPDATE users SET reputation = reputation + $2 WHERE user_id = (
    SELECT donor_id FROM keys WHERE id = last_giveaway.key;
) RETURNING *;
```
You may skip that `with` statement and just pass the lastGiveaway variable.

2021-07-20 17:13 UTC, dannyhpy commented on src/commands/rep.ts
> +      if (lastGiveaway.rep_given === true) {
I can but does it really change anything?

2021-07-20 18:02 UTC, Bluenix2 commented on src/commands/rep.ts
> +      if (lastGiveaway.rep_given === true) {
Not really no, but I guess it's more about readability. Since we know that the logic should go `if`, and if that failed then check that condition.

2021-07-24 23:10 UTC, Bluenix2 commented on src/commands/rep.ts
> +          ) AS last_giveaway;
You already have the `lastGiveaway` const. You can skip this and pass that (you will need to change the parameters.

2021-07-24 23:10 UTC, Bluenix2 commented on src/commands/rep.ts
> +      if (lastGiveaway == null) return interaction.reply("You cannot use this command at the moment.");
Something I've noticed is that you're a bit inconsistent with which quotes to use. I think I've so far tried to use single-quotes (mostly stemming from my Python background probably). Do you prefer double-quotes/see it more often?

2021-07-24 23:10 UTC, Bluenix2 commented on src/commands/rep.ts
> +  async give(interaction: CommandInteraction, increment: number): Promise<void> {
Might be worth it to add a small JSDoc explaining why we made this?

2021-07-24 23:10 UTC, Bluenix2 commented on src/commands/rep.ts
> +    return interaction.reply('A good reputation point has been given.');
Currently this will both send a failure message and a `'A good reputation point has been given.'` even when it fails.

You should make `give()` return either undefined (so that we can keep the one-liners) or true (if it was successful). Then you can use this return-value to see if you should send a confirmation message.

2021-07-24 23:10 UTC, Bluenix2 commented on src/commands/rep.ts
> +    return interaction.reply('A bad reputation point has been given.');
See my comment on `good()`.

2021-07-24 23:10 UTC, Bluenix2 commented on src/database/KeyTable.ts
> +      text:'INSERT INTO keys (donor_id, value, message) VALUES ($1, $2, $3) RETURNING *;',
Oops, there should be a space before the `'`.

2021-07-24 23:10 UTC, Bluenix2 commented on src/database/UserTable.ts
> +  claimed_keys: number;
Do you want to make the necessary change to have this work?

You will have to change some things inside `core/GiveawayManager.ts`.

2021-07-25 10:45 UTC, maxerbox commented on src/commands/rep.ts
> +      if (lastGiveaway == null) return interaction.reply("You cannot use this command at the moment.");
I think @dannyhpy should use your eslint rc file

2021-10-10 16:45 UTC, Bluenix2 commented
@dannyhpy can you finish this or do you perhaps want me to take over?

2021-10-11 01:26 UTC, dannyhpy commented
> @dannyhpy can you finish this or do you perhaps want me to take over?

@Bluenix2 Sure, feel free to take over

2021-10-11 08:15 UTC, Bluenix2 commented
@dannyhpy is there anything else you rather work on, or do you not really have time?

2022-09-05 20:01 UTC, closed without merging